# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: List
  type: object
  default: [ One, Two, Three ]

- name: Boolean
  displayName: Display number of items
  type: boolean

- name: AdditionalVariables
  type: object
  default:
    qux: quux

- name: AdditionalStep
  type: step
  default:
    script: echo '¡Hola, Mundo!'
    displayName: Display Hello World in Spanish

variables:
  foo: bar
  ${{ insert }}: ${{ parameters.AdditionalVariables }}

steps:
- ${{ if parameters.Boolean }}:
  - script: echo 'Items in list = ${{ length(parameters.List) }}'
    displayName: Display number of items (template expression)

- script: echo 'Items in list = ${{ length(parameters.List) }}'
  displayName: Display number of items (condition)
  condition: ${{ parameters.Boolean }} 

- ${{ each item in parameters.List }}:
  - script: echo 'Item = ${{ item }}'
    displayName: Display item from array

- script: echo 'qux = $(qux)'
  displayName: Display variable qux

- ${{ parameters.AdditionalStep }}