# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: Environment
  type: string
  values:
  - Development
  - Production

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: ${{ parameters.Environment }}Variables
- name: RuntimeExpressionIndex
  value: $[ eq(variables['foo'], 'production') ]
- name: RuntimeExpressionPropertyDereference
  value: $[ ne(variables.foo, 'production') ]

steps:
- script: echo foo = $(foo)
  displayName: Display runtime variable foo

- script: echo parameters.Environment = ${{ parameters.Environment }}
  displayName: Display compile time parameter Environment

- script: echo foo == 'production' --> $(RuntimeExpressionIndex)
  displayName: Runtime expression - index syntax

- script: echo foo != 'production' --> $(RuntimeExpressionPropertyDereference)
  displayName: Runtime expression - property dereference syntax 

- script: echo '##vso[task.setvariable variable=localVar]foo'
  displayName: Set variable localVar
  name: SetLocalVariable

- script: echo localVar = $(localVar)
  displayName: Display variable localVar