# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: BooleanValue
  displayName: Boolean Value
  type: boolean
  default: true

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: DevelopmentVariables

steps:
- script: echo Hello World!
  displayName: Only runs when MultipleChoiceRadio = true
  condition: eq(${{ parameters.BooleanValue }}, true)

- script: echo Hello World!
  displayName: Only runs when branch is 6-conditions
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/6-conditions')

- script: echo Hello World!
  displayName: Only runs when variable foo from variable group = development
  condition: eq(variables['foo'], 'development')

- script: 0/0

- script: echo Hello World!
  displayName: Only runs when the previous step fails
  condition: failed()

- script: echo Merging $(Build.SourceBranch) into $(System.PullRequest.TargetBranch)
  displayName: Only runs when in a pull request
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: echo Hello World!
  displayName: Only runs when MultipleChoiceRadio = true, branch = 6-conditions and variable = development
  condition: and(
                eq(${{ parameters.BooleanValue }}, true),
                eq(variables['Build.SourceBranch'], 'refs/heads/6-conditions'),
                eq(variables['foo'], 'development')
             )