# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: TextValue
  displayName: Text Value
  type: string
  default: Default text value...
- name: MultipleChoiceRadio
  displayName: Multiple Choice radio (up to 3)
  type: string
  values:
  - a
  - b
  - c
  default: b
- name: MultipleChoiceDropdown
  displayName: Multiple Choice dropdown (4 and more)
  type: string
  values:
  - a
  - b
  - c
  - d
  default: c
- name: NumericValue
  displayName: Numeric Value
  type: number
- name: MultipleNumericChoice
  displayName: Multiple Numeric Choice
  type: number
  values:
  - 1
  - 2
  - 3
  - 999
  default: 999
- name: BooleanValue
  displayName: Boolean Value
  type: boolean

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo TextValue = ${{ parameters.TextValue }}
  displayName: MultipleChoiceRadio = ${{ parameters.MultipleChoiceRadio }}
  condition: eq(${{ parameters.BooleanValue }}, true)
- script: echo NumericValue = ${{ parameters.NumericValue }}
- script: echo MultipleNumbericChoice = $(MultipleNumbericChoice)
