# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
  name: Environment
  type: string
  values:
  - development
  - production
  - foo

trigger:
- main

variables:
- template: variables\${{ parameters.Environment }}.yml

pool:
  vmImage: ubuntu-latest

stages:
- template: stages\build-stage.yml