# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GlobalVariable: global

stages:
- stage:
  displayName: Build stage
  variables:
    StageVariable: stage

  jobs:
  - job:
    displayName: Agent job
    variables:
      JobVariable: job

    steps:
    - script: echo GlobalVariable = $(GlobalVariable)
      displayName: Display global variable
    
    - script: echo StageVariable = $(StageVariable)
      displayName: Display stage variable
    
    - script: echo JobVariable = $(JobVariable)
      displayName: Display job variable