# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: TextValue
  displayName: Text Value
  type: string
  default: Default text value...
- name: MultipleChoiceRadio
  displayName: Multiple Choice radio (up to 3)
  type: string
  values:
  - a
  - b
  - c
  default: b
- name: MultipleChoiceDropdown
  displayName: Multiple Choice dropdown (4 and more)
  type: string
  values:
  - a
  - b
  - c
  - d
  default: c
- name: NumericValue
  displayName: Numeric Value
  type: number
- name: MultipleNumericChoice
  displayName: Multiple Numeric Choice
  type: number
  values:
  - 1
  - 2
  - 3
  - 999
  default: 999
- name: BooleanValue
  displayName: Boolean Value
  type: boolean
- name: ObjectValue
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one  
    - two  
    - three  
    nested:
      one: apple
      two: pear
      count: 3
- name: myStep
  type: step
  default:
    script: echo my step 

- name: mySteplist
  type: stepList
  default:
    - script: echo step one  
    - script: echo step two  

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: Run a one-line script

- ${{ parameters.myStep }}
- ${{ parameters.mySteplist }}

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: Run a multi-line script
