# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  displayName: Build stage
  jobs:
  - job:
    displayName: Agent job 1
    steps:
    - script: echo Hello, world from YAML pipeline!
      displayName: Hello World
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: Run a multi-line script

- stage:
  displayName: Deployment release
  jobs:
  - deployment:
    displayName: Development release
    environment: DevelopmentEnvironment
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying to Development environment"

- stage:
  displayName: Production release
  jobs:
  - deployment:
    displayName: Production release
    environment: ProductionEnvironment
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying to Production environment"