# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: Environment
  type: string
  values:
  - Development
  - Production

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: ${{ parameters.Environment }}Variables

steps:
- script: echo foo = $(foo)