# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: TextValue
  displayName: Text Value
  type: string
  default: Default text value...
- name: MultipleChoice
  displayName: Multiple Choice
  type: string
  values:
  - a
  - b
  - c
  default: b
- name: NumericValue
  displayName: Numeric Value
  type: number
- name: MultipleNumericChoice
  displayName: Multiple Numeric Choice
  type: number
  values:
  - 1
  - 2
  - 3
  - 999
  default: 999
- name: BooleanValue
  displayName: Boolean Value
  type: boolean
- name: ObjectValue
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one  
    - two  
    - three  
    nested:
      one: apple
      two: pear
      count: 3

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
