jobs:
- job: BuildJob
  steps:
  - template: ..\steps\component-list-parameter.yml
    parameters:
      Steps:
      - script: echo 'Injected!'
      - template: ..\steps\hello-world.yml
      - script: echo 'Third step...'